# Generated by Django 5.1.1 on 2024-10-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('hardware_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=100)),
                ('noinventario', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fields_3', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_4', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_5', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_6', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_7', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_8', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_9', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_10', models.CharField(blank=True, max_length=100, null=True)),
                ('fields_11', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'accountinfo',
            },
        ),
    ]
